<?php
/**
 * Generated by "Autoload generator"
 * @link http://github.com/dmkuznetsov/php-autoloader
 * @date 2013-11-16 21:22
 */
function __dm_autoload_fotki($name)
{
    $map = array(
        'Yandex\\Fotki\\Api' => 'Yandex/Fotki/Api.php',
        'Yandex\\Fotki\\ApiAbstract' => 'Yandex/Fotki/ApiAbstract.php',
        'Yandex\\Fotki\\Api\\Album' => 'Yandex/Fotki/Api/Album.php',
        'Yandex\\Fotki\\Api\\AlbumsCollection' => 'Yandex/Fotki/Api/AlbumsCollection.php',
        'Yandex\\Fotki\\Api\\CollectionAbstract' => 'Yandex/Fotki/Api/CollectionAbstract.php',
        'Yandex\\Fotki\\Api\\FimpAuth' => 'Yandex/Fotki/Api/FimpAuth.php',
        'Yandex\\Fotki\\Api\\Photo' => 'Yandex/Fotki/Api/Photo.php',
        'Yandex\\Fotki\\Api\\PhotosCollection' => 'Yandex/Fotki/Api/PhotosCollection.php',
        'Yandex\\Fotki\\Api\\ServiceDocument' => 'Yandex/Fotki/Api/ServiceDocument.php',
        'Yandex\\Fotki\\Api\\Tag' => 'Yandex/Fotki/Api/Tag.php',
        'Yandex\\Fotki\\Api\\TagsCollection' => 'Yandex/Fotki/Api/TagsCollection.php',
        'Yandex\\Fotki\\Encrypt' => 'Yandex/Fotki/Encrypt.php',
        'Yandex\\Fotki\\Exception' => 'Yandex/Fotki/Exception.php',
        'Yandex\\Fotki\\Exception\\Api' => 'Yandex/Fotki/Exception/Api.php',
        'Yandex\\Fotki\\Exception\\Api\\Album' => 'Yandex/Fotki/Exception/Api/Album.php',
        'Yandex\\Fotki\\Exception\\Api\\AlbumsCollection' => 'Yandex/Fotki/Exception/Api/AlbumsCollection.php',
        'Yandex\\Fotki\\Exception\\Api\\Auth' => 'Yandex/Fotki/Exception/Api/Auth.php',
        'Yandex\\Fotki\\Exception\\Api\\Photo' => 'Yandex/Fotki/Exception/Api/Photo.php',
        'Yandex\\Fotki\\Exception\\Api\\PhotosCollection' => 'Yandex/Fotki/Exception/Api/PhotosCollection.php',
        'Yandex\\Fotki\\Exception\\Api\\ServiceDocument' => 'Yandex/Fotki/Exception/Api/ServiceDocument.php',
        'Yandex\\Fotki\\Exception\\Api\\StopIteration' => 'Yandex/Fotki/Exception/Api/StopIteration.php',
        'Yandex\\Fotki\\Exception\\Api\\Tag' => 'Yandex/Fotki/Exception/Api/Tag.php',
        'Yandex\\Fotki\\Exception\\Api\\TagsCollection' => 'Yandex/Fotki/Exception/Api/TagsCollection.php',
        'Yandex\\Fotki\\Exception\\CurlError' => 'Yandex/Fotki/Exception/CurlError.php',
        'Yandex\\Fotki\\Exception\\ServerError' => 'Yandex/Fotki/Exception/ServerError.php',
        'Yandex\\Fotki\\Transport' => 'Yandex/Fotki/Transport.php',
    );
    if (isset($map[$name])) {
        require  dirname(__FILE__) . "/" . $map[$name];
    }
}

spl_autoload_register('__dm_autoload_fotki');
